name: Run Unit Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  unit-test:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    # Only run job if untagged as release. Will run for all PRs and release PRs during the first run.
    strategy:
      matrix:
        java: [8, 11, 16]

    steps:
    - uses: actions/checkout@v2
    - name: Cache Local Maven Repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Run Unit Tests With Maven
      run: mvn -B clean test --file pom.xml

    - name: Archive Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-reports-jdk${{ matrix.java }}
        path: ./**/target/surefire-reports

    - name: Save Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: liquibase-postgresql
        path: |
          target/*.jar

  dependabot:
    name: Merge dependabot
    runs-on: ubuntu-latest
    needs: unit-test
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.1

      - name: Approve patch and minor updates
        if: ${{steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor'}}
        run: |
          gh pr merge --auto --merge "$PR_URL"
          gh pr review $PR_URL --approve -b "I'm **approving** this pull request because **it includes a patch or minor update**"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
